version: '3.8'

services:
  fastapi-ddd:
    container_name: fastapi-ddd
    build:
      context: .
      dockerfile: Dockerfile
    command: python ./src/server.py
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@ddd-db:5432/fastapi_ddd
    depends_on:
      - ddd-db
    links:
      - ddd-db
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: [ "CMD-SHELL", "nc -z ddd-db 5432" ]
      interval: 5s
      timeout: 5s
      retries: 5

  ddd-db:
    image: postgres:15-alpine
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_DB=fastapi_ddd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
